### ISSUE TITLE
Bug when pasting nodes

### ISSUE THREAD

**Issue by hsauro** [evilnose/PyRKViewer#55]
1. Add some nodes

2. Select a bunch

3. Copy (Ctrl-C)

4. Paste (Ctrl.V)

Crash:

PS D:\Documents\Tellurium\GitHubProjects\PyRKViewer> python main.py
Initializing RKViewer...
Traceback (most recent call last):
  File "D:\Documents\Tellurium\GitHubProjects\PyRKViewer\rkviewer\view.py", line 393, in <lambda>
    lambda _: canvas.Paste(), entries, key=(wx.ACCEL_CTRL, ord('V')))
  File "D:\Documents\Tellurium\GitHubProjects\PyRKViewer\rkviewer\canvas\canvas.py", line 1273, in Paste
    for id_ in pasted_ids})
  File "D:\Documents\Tellurium\GitHubProjects\PyRKViewer\rkviewer\canvas\utils.py", line 129, in set_item
    self.notify()
  File "D:\Documents\Tellurium\GitHubProjects\PyRKViewer\rkviewer\canvas\utils.py", line 107, in notify
    observer.update(self._item)
  File "D:\Documents\Tellurium\GitHubProjects\PyRKViewer\rkviewer\canvas\canvas.py", line 204, in <lambda>
    selection_obs = Observer(lambda _: self._SelectionChanged())
  File "D:\Documents\Tellurium\GitHubProjects\PyRKViewer\rkviewer\canvas\canvas.py", line 1101, in _SelectionChanged
    compartment_indices=comp_idx))
  File "D:\Documents\Tellurium\GitHubProjects\PyRKViewer\rkviewer\events.py", line 364, in post_event
    callback(evt)
  File "D:\Documents\Tellurium\GitHubProjects\PyRKViewer\rkviewer\view.py", line 102, in OnSelectionDidUpdate
    self.node_form.UpdateSelection(evt.node_indices, comps_selected=should_show_comps)
  File "D:\Documents\Tellurium\GitHubProjects\PyRKViewer\rkviewer\forms.py", line 497, in UpdateSelection
    self.UpdateAllFields()
  File "D:\Documents\Tellurium\GitHubProjects\PyRKViewer\rkviewer\forms.py", line 738, in UpdateAllFields
    nodes = get_nodes_by_idx(self._nodes, self._selected_idx)
  File "D:\Documents\Tellurium\GitHubProjects\PyRKViewer\rkviewer\canvas\utils.py", line 17, in get_nodes_by_idx
    assert len(ret) == len(indices)
AssertionError

**Comment by evilnose** [comment]
Fix pushed to master.
